services:
  appgroup.contabilidade.webapi:
    image: ${DOCKER_REGISTRY-}appgroupcontabilidadewebapi
    build:
      context: .
      dockerfile: src/AppGroup.Contabilidade.WebApi/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

  portainer:
    image: portainer/portainer-ce

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

volumes:
  portainer_data:
  elasticsearch_data:
  sqlserver_data:
    name: sqlserver
