// <auto-generated />
using System;
using AppGroup.Contabilidade.Infrastructure.Database.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppGroup.Contabilidade.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppGroup.Contabilidade.Domain.Entities.ContaContabil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("AceitaLancamentos")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("IdPai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPai");

                    b.ToTable("ContasContabeis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55ad855d-c9e8-4566-8ef0-fe189acc0533"),
                            AceitaLancamentos = false,
                            Codigo = "1",
                            Nome = "Receitas",
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("f1ceaafe-3d8f-4dbc-aac0-e1e27f8ec436"),
                            AceitaLancamentos = false,
                            Codigo = "2",
                            Nome = "Despesas",
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("AppGroup.Contabilidade.Domain.Entities.ContaContabil", b =>
                {
                    b.HasOne("AppGroup.Contabilidade.Domain.Entities.ContaContabil", "ContaPai")
                        .WithMany("SubContas")
                        .HasForeignKey("IdPai")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ContaPai");
                });

            modelBuilder.Entity("AppGroup.Contabilidade.Domain.Entities.ContaContabil", b =>
                {
                    b.Navigation("SubContas");
                });
#pragma warning restore 612, 618
        }
    }
}
